export default function AboutPage() {
  return (
    <main className="grid px-5 py-20 justify-center justify-items-center">
      <section className="grid justify-center justify-items-center pb-12 gap-4">

        <h1 className="text-2xl font-bold">Our History</h1>
        <p className="max-w-[60ch]">Daniel had worked in the corporate world of physical therapy for many years before finally opening his own practice. As time went on, more and more offices began relying on technicians and assistants for appointments, rather than giving their patients dedicated time with a physical therapist. As a passionate and experienced physical therapist, Daniel felt this was unfair to the people coming in for help. Most days, he was only able to give his patients a fraction of his time during an hour-long appointment. He knew this was simply not enough to efficiently and effectively support each person's rehabilitation. It was time for a change.</p>
        <p className="max-w-[60ch]">In October of 2021, Daniel and his wife Rebecca opened VBNC Physical Therapy. Daniel was eager to bring his passion for physical therapy and people together into a brand-new, welcoming space. For Daniel, it always has been and always will be critical to focus on patients first, and he now has the means to provide an exceptional experience to his patients like never before.</p>
      </section>
      <section className="grid justify-center justify-items-center pb-12 gap-4">
        <h2 className="text-2xl font-bold">Our Mission</h2>
        <p className="max-w-[60ch]">The VBNC Physical Therapy mission is to serve people with dizziness, balance disturbances, and various orthopedic conditions including headaches with a quality one-on-one approach. Our vision is to focus holistically on each individual patient and develop treatment plans that will promptly allow them to return to their personal life experiences.</p>
        <p className="max-w-[60ch]">VBNC Physical Therapy emphasizes a holistic approach centered around each individual person, and will always provide full hour-long appointments with a physical therapist. This time is critical for proper, expedited, and successful rehabilitation and will never be compromised. We understand the importance of spending quality time building rapport with each client as well as analyzing and evaluating symptoms, progress, and setbacks. By committing ourselves to uninterrupted appointments with each patient, we know that our clients will experience the success they have been waiting for.</p>
      </section>
      <section className="grid justify-center justify-items-center pb-12 gap-4">
        <h2 className="text-2xl font-bold">Meet Daniel</h2>
        <p className="max-w-[60ch]">Daniel is originally from Paraguay, where he first became a licensed physical therapist. During his schooling, Daniel was exposed to many different and successful methodologies for treating various conditions. Beyond the academic side, the most impactful learning opportunity was in how his teachers treated their patients. Rather than simply approaching them as a symptom, he learned how to really see them as individuals and treated them with this mindset. This created a great shift in Daniel's love for physical therapy and helped him connect more with people within his practice.</p>
        <p className="max-w-[60ch]">Daniel later relocated to the Pacific Northwest and obtained his license to practice physical therapy in the state of Washington. After going through all of the necessary coursework and credentialing, Daniel began working for a physical therapy corporation providing care to people in the area. He worked alongside many impactful professionals, including fellow physical therapist Mark Looper, who introduced him to what he called “the hidden link theory.” This research was very influential in Daniel's professional development and is used in his practice today. Over the years, Daniel broadened his scope of practice beyond orthopedic conditions and began to study and explore balance and vertigo conditions and treatment methods. He quickly developed a passion for all 3 of these areas and was eager to help people overcome their struggles. Daniel found fulfillment in seeing progress and improvements in his patients as they worked with him.</p>
        <p className="max-w-[60ch]">In 2021, Daniel and his wife Rebecca opened VBNC Physical Therapy to provide a better physical therapy experience to the community. They currently live in Lacey with their 4 young children. They love God and are grateful to be involved with a strong local Christian community through the Church in Olympia. During their free time, they enjoy spending time in the great outdoors and doing family activities. As a native to Paraguay, Daniel is bilingual and is able to help Spanish-speaking patients.</p>
        <p className="max-w-[60ch]">Daniel was born with a condition called retinitis pigmentosa, which causes a gradual loss of vision. He himself does therapy to adjust to his condition and current level of vision. This experience has helped him develop an even deeper understanding of how people can struggle with different health conditions and the role this plays in their lives. Through this firsthand experience and professional expertise, Daniel is truly able to relate to patients dealing with a chronic condition in a more compassionate and comprehensive way.</p>
      </section>
    </main>
  )
}